<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ADS67" name="exe.HS_Record_Type_DataValidation_TS003" tests="5" failures="0" timestamp="5 Jul 2017 10:00:49 GMT" time="2.711" errors="1">
  <testcase name="HS_Record_Type_AS_HS_Price_Increase_TC007" time="0.116" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_Debt_Cancel_TC004" time="2.134" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_Debt_Delinquent_Letter_TC005" time="0.205" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_NULL_TC008" time="0.109" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_HS_DownGrade_TC006" time="0.147" classname="exe.HS_Record_Type_DataValidation_TS003">
    <error type="junit.framework.AssertionFailedError" message="HS_DownGrade counts are Not Equal expected:&lt;14&gt; but was:&lt;13&gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_DownGrade counts are Not Equal expected:<14> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Record_Type_DataValidation_TS003.HS_Record_Type_AS_HS_DownGrade_TC006(HS_Record_Type_DataValidation_TS003.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- HS_Record_Type_AS_HS_DownGrade_TC006 -->
</testsuite> <!-- exe.HS_Record_Type_DataValidation_TS003 -->
